site_name: Hydrophone Shield design documentation
repo_url: https://github.com/mcgill-robotics/auv-embedded-2026/

nav:
    - Home: index.md
    - Design Iterations:
        - version 1.0: design/v1.0/change_log.md
        - version 1.1: design/v1.1/change_log.md
    - Design:
        - Signal chain design: design/signal-chain.md
        - Power components : design/power.md
        - Analog frontend : design/afe.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js